solr:
  host: localhost
  port: 8983
  core: playground

dbconfig:
  connectionLimit: 10
  host: localhost
  user: root
  password: password
  database: rss

solr_service:
  host: 0.0.0.0
  port: 50051
